### ISSUE TITLE
Required parameter is treated as optional by aaz-dev

### ISSUE THREAD

**Issue by blackchoey** [Azure/aaz-dev-tools#340]
Based on below API spec snippets, the `title` parameter should be required:
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/apicenter/resource-manager/Microsoft.ApiCenter/stable/2024-03-01/apicenter.json#L2109-L2118
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/apicenter/resource-manager/Microsoft.ApiCenter/stable/2024-03-01/apicenter.json#L3760-L3779

But aaz-dev treated this parameter (--title) as optional:
![image](https://github.com/Azure/aaz-dev-tools/assets/16605901/9a4502a7-9cb7-41da-8e03-6d72a340a387)

**Comment by kairu-ms** [comment]
Hi @blackchoey, that's because the `properties` defined in this [schema](https://github.com/Azure/azure-rest-api-specs/blob/f46542f7b4e35acfaab55977a9df65d6f256b818/specification/apicenter/resource-manager/Microsoft.ApiCenter/stable/2024-03-01/apicenter.json#L3721-L3729) is not marked as required. And because the title and lifecycle stage are the sub prop of it, so the passing of requirement ends here.
